// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVbZ_d6J3yctEMwQVFRtW07Zv6c7qChd4',
    appId: '1:88318923623:web:571d0b5380eb5baf72d5c2',
    messagingSenderId: '88318923623',
    projectId: 'tiem-cat-vung-me-f43a1',
    authDomain: 'tiem-cat-vung-me-f43a1.firebaseapp.com',
    storageBucket: 'tiem-cat-vung-me-f43a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49Ynm629wjVlxzcqQE6GzSJGytq2mzHI',
    appId: '1:88318923623:android:0ff14a57118f474372d5c2',
    messagingSenderId: '88318923623',
    projectId: 'tiem-cat-vung-me-f43a1',
    storageBucket: 'tiem-cat-vung-me-f43a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoXvy0AUulLFT6IrX24N_6JlURdT4AECU',
    appId: '1:88318923623:ios:d378e5140ac7633f72d5c2',
    messagingSenderId: '88318923623',
    projectId: 'tiem-cat-vung-me-f43a1',
    storageBucket: 'tiem-cat-vung-me-f43a1.appspot.com',
    iosBundleId: 'com.example.tiemCatVungMe',
  );
}
